name: plugins
on:
# Run CI against all pushes (direct commits) and Pull Requests
# push: ensure we always run tests
# pull_requests: skip if PR only modifies "./roles/"
  pull_request:

jobs:
  sanity:
    name: Sanity (Ⓐ${{ matrix.ansible }}+py${{ matrix.python }})
    strategy:
      matrix:
        ansible:
          - devel
        python:
          - 3.7
    runs-on: ubuntu-latest
    steps:

      # ansible-test requires the collection to be in a directory in the form
      # .../ansible_collections/NAMESPACE/COLLECTION_NAME/

      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ansible_collections/community/zabbix

      - name: Set up Python ${{ matrix.ansible }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      # Install the head of the given branch (devel, stable-2.10)
      - name: Install ansible-base (${{ matrix.ansible }})
        run: pip install https://github.com/gundalow/ansible/archive/github_checks.tar.gz --disable-pip-version-check

      # run ansible-test sanity inside of Docker.
      # The docker container has all the pinned dependencies that are required.
      # Explicity specify the version of Python we want to test
      #
      # Call without --color
      - name: Run sanity tests
        run: ansible-test sanity --docker -v --python ${{ matrix.python }}
        working-directory: ./ansible_collections/community/zabbix
